In [7]:
import os
import numpy as np
import pandas as pd

In [8]:
import warnings
warnings.filterwarnings("ignore")

In [9]:
pwd

'C:\\Users\\Pavan\\Desktop\\Hackathon'

In [10]:
os.chdir('C:/Users/Pavan/Desktop/Hackathon')

In [11]:
data = pd.read_csv("train.csv",na_values="?")

FileNotFoundError: [Errno 2] File b'train.csv' does not exist: b'train.csv'

In [6]:
data.shape

NameError: name 'data' is not defined

In [ ]:
data.head()

Check the value of counts in lepton_pT

In [ ]:
data.nunique()

In [ ]:
data.dtypes

In [ ]:
cat_cols = data.columns[data.nunique() <= 5]
cat_cols

In [ ]:
num_cols = data.columns[data.nunique() > 5]
num_cols

# Drop columns which are not significant

In [ ]:
#we are removing ID since it has all the unique values which means number of rows(68636) is equal to number of unique values of ID
data.drop(["id"], axis = 1, inplace=True)
num_cols = data.columns[data.nunique() > 5]

In [ ]:
data.head()

In [ ]:
data.isna().sum()

In [ ]:
data.isnull().sum()

In [ ]:
y=data.loc[:, "class"]
y

In [ ]:
X= data.loc[:,data.columns!='class']
X

In [ ]:
print(X.shape, y.shape)

In [ ]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 122)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

In [ ]:
X_train.shape[1]

In [ ]:
y_train.value_counts()

In [ ]:
print(y_train.value_counts()/X_train.shape[0])

In [ ]:
print(y_test.value_counts()/X_test.shape[0])

In [8]:
import numpy as np
from sklearn.datasets.samples_generator import make_blobs
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix
from sklearn import svm
from sklearn.svm import SVC

In [9]:
linear_svm = SVC(kernel='linear', C=1, random_state=0)

In [11]:
linear_svm.fit(X=X_train, y= y_train)

NameError: name 'X_train' is not defined

In [29]:
## Predict
train_predictions = linear_svm.predict(X_train)
test_predictions = linear_svm.predict(X_test)

### Train data accuracy
from sklearn.metrics import accuracy_score,f1_score

print("TRAIN Conf Matrix : \n", confusion_matrix(y_train, train_predictions))
print("\nTRAIN DATA ACCURACY",accuracy_score(y_train,train_predictions))
print("\nTrain data f1-score for class '1'",f1_score(y_train,train_predictions,pos_label=1))
print("\nTrain data f1-score for class '2'",f1_score(y_train,train_predictions,pos_label=0))

### Test data accuracy
print("\n\n--------------------------------------\n\n")

print("TEST Conf Matrix : \n", confusion_matrix(y_test, test_predictions))
print("\nTEST DATA ACCURACY",accuracy_score(y_test,test_predictions))
print("\nTest data f1-score for class '1'",f1_score(y_test,test_predictions,pos_label=1))
print("\nTest data f1-score for class '2'",f1_score(y_test,test_predictions,pos_label=0))

TRAIN Conf Matrix : 
 [[11282 14575]
 [ 5162 23889]]

TRAIN DATA ACCURACY 0.6405441829970132

Train data f1-score for class '1' 0.7076649633414797

Train data f1-score for class '2' 0.5334152856906457


--------------------------------------


TEST Conf Matrix : 
 [[2856 3644]
 [1258 5970]]

TEST DATA ACCURACY 0.6429195804195804

Test data f1-score for class '1' 0.7089419308870681

Test data f1-score for class '2' 0.5381571509327303


In [30]:
unseendata=pd.read_csv('test.csv', na_values=["?", "", "null"])

In [32]:
unseendata_ids = unseendata.loc[:, "id"]
unseendata.drop(["id"], axis = 1, inplace=True)

In [33]:
unseendata.loc[29413, :]

class                       1.000000
lepton_pT                   0.708611
lepton_eta                  1.190136
lepton_phi                  0.593009
missing_energy_magnitude    1.899366
missing_energy_phi         -0.111872
jet1pt                      0.871276
jet1eta                     0.982283
jet1phi                    -1.684691
jet1b.tag                   2.173076
jet2pt                      0.653187
jet2eta                     1.648481
jet2phi                    -1.415022
jet2b.tag                   2.214872
jet3pt                      0.956961
jet3eta                     1.482058
jet3phi                     0.697208
jet3b.tag                   0.000000
jet4pt                      0.609978
jet4eta                     1.797605
jet4phi                          NaN
jet4b.tag                        NaN
m_jj                             NaN
m_jjj                            NaN
m_lv                             NaN
m_jlv                            NaN
m_bb                             NaN
m

In [37]:
from sklearn.impute import SimpleImputer
cat_imputer = SimpleImputer(strategy='most_frequent')
cat_imputer.fit(X_train)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='most_frequent', verbose=0)

In [38]:
X_unseendata=unseendata.loc[:,unseendata.columns!='class']

In [39]:
y_unseendata=unseendata.loc[:, "class"]

In [40]:
X_unseendata = pd.DataFrame(cat_imputer.transform(X_unseendata), columns=X_unseendata.columns)

In [41]:
X_unseendata.isnull().sum()

lepton_pT                   0
lepton_eta                  0
lepton_phi                  0
missing_energy_magnitude    0
missing_energy_phi          0
jet1pt                      0
jet1eta                     0
jet1phi                     0
jet1b.tag                   0
jet2pt                      0
jet2eta                     0
jet2phi                     0
jet2b.tag                   0
jet3pt                      0
jet3eta                     0
jet3phi                     0
jet3b.tag                   0
jet4pt                      0
jet4eta                     0
jet4phi                     0
jet4b.tag                   0
m_jj                        0
m_jjj                       0
m_lv                        0
m_jlv                       0
m_bb                        0
m_wbb                       0
m_wwbb                      0
dtype: int64

In [42]:
X_unseendata.nunique()

lepton_pT                   13786
lepton_eta                   7895
lepton_phi                  10476
missing_energy_magnitude    29132
missing_energy_phi          29138
jet1pt                      17678
jet1eta                      7838
jet1phi                     10383
jet1b.tag                       5
jet2pt                      15784
jet2eta                      8145
jet2phi                     10507
jet2b.tag                       5
jet3pt                      13492
jet3eta                      8498
jet3phi                     10487
jet3b.tag                       5
jet4pt                      10920
jet4eta                      8978
jet4phi                      6234
jet4b.tag                       3
m_jj                        28629
m_jjj                       26075
m_lv                        20086
m_jlv                       27167
m_bb                        27698
m_wbb                       27978
m_wwbb                      28236
dtype: int64

In [43]:
unseendata_predictions = linear_svm.predict(X_unseendata)

In [44]:
print("unseendata Conf Matrix : \n", confusion_matrix(y_unseendata, unseendata_predictions))
print("\nunseendata DATA ACCURACY",accuracy_score(y_unseendata,unseendata_predictions))
print("\nunseendata data f1-score for class '1'",f1_score(y_unseendata,unseendata_predictions,pos_label=1))
print("\nunseendata data f1-score for class '2'",f1_score(y_unseendata,unseendata_predictions,pos_label=0))


unseendata Conf Matrix : 
 [[ 6157  7709]
 [ 2876 12672]]

unseendata DATA ACCURACY 0.6401373495614333

unseendata data f1-score for class '1' 0.7053911881766818

unseendata data f1-score for class '2' 0.5377527402943361


In [77]:
final_output=pd.DataFrame({'id':unseendata_ids, 'prediction':unseendata_predictions})
id_n_prediction = ["id", "prediction"]
final_output = final_output.loc[:,id_n_prediction]
#final_output.to_csv("final_output01.csv")
final_output


id  prediction
0      68637           1
1      68638           1
2      68639           1
3      68640           1
4      68641           1
...      ...         ...
29409  98046           1
29410  98047           1
29411  98048           0
29412  98049           0
29413  98050           0

[29414 rows x 2 columns]

In [2]:
final_output.to_csv("final_output01.csv")

NameError: name 'final_output' is not defined

In [1]:
import pandas as pd

In [2]:
x = pd.read_csv("final_output01.csv",)

In [3]:
x.head()

id  prediction
0  68637           1
1  68638           1
2  68639           1
3  68640           1
4  68641           1

In [7]:
x.shape


(29414, 2)